// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPA8CiLrVgVk9z9FCdpjtZ31O-x3PSpac',
    appId: '1:707195877058:android:ec3f1734e83c9594df2d5b',
    messagingSenderId: '707195877058',
    projectId: 'nisha-sanjesh-donation',
    storageBucket: 'nisha-sanjesh-donation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUhDIWA3TZTrlwgZJLbroHaowHPPjUb8k',
    appId: '1:707195877058:ios:b2c5e8e7d27a8eacdf2d5b',
    messagingSenderId: '707195877058',
    projectId: 'nisha-sanjesh-donation',
    storageBucket: 'nisha-sanjesh-donation.appspot.com',
    androidClientId: '707195877058-td24el3b89u6j8uvm6t97poudju1r4tk.apps.googleusercontent.com',
    iosClientId: '707195877058-mehp12k8bnr708kqsgi1o1m68kjektih.apps.googleusercontent.com',
    iosBundleId: 'com.example.donationApp',
  );
}
